import{a as b,S as L,i}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&u(h)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const w="47675764-87f77a78ce9e5d021dcf81100",v="https://pixabay.com/api/";async function m(e,t){const o=new URLSearchParams({key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await b.get(v,{params:o})).data}const f=document.querySelector(".gallery");let p;function g(e){const t=e.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" width="360"/>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </a>
  `).join("");f.insertAdjacentHTML("beforeend",t),p?p.refresh():p=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}function S(){f.innerHTML=""}function y(e){e.classList.remove("hidden")}function l(e){e.classList.add("hidden")}const R=document.getElementById("search-form"),q=document.querySelector(".search-input"),n=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");let c="",a=1;R.addEventListener("submit",async e=>{if(e.preventDefault(),c=q.value.trim(),!c){i.error({message:"Please enter a search term.",position:"topRight",backgroundColor:"#ef4040",class:"custom-toast-error"});return}S(),y(n),d.classList.add("hidden"),a=1;try{const t=await m(c,a);if(l(n),t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query.",position:"topRight",backgroundColor:"#ef4040",class:"custom-toast-error"});return}g(t.hits),t.totalHits>a*15&&d.classList.remove("hidden")}catch(t){l(n),i.error({message:"Something went wrong. Please try again.",position:"topRight",backgroundColor:"#ef4040",class:"custom-toast-error"}),console.error(t)}});d.addEventListener("click",async()=>{a+=1,y(n);try{const e=await m(c,a);if(l(n),g(e.hits),e.hits.length===0||e.totalHits<=a*15){i.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d.classList.add("hidden");return}const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch(e){l(n),i.error({message:"Something went wrong. Please try again.",position:"topRight"}),console.error(e)}});
//# sourceMappingURL=index.js.map
